# Generated by Django 5.1.1 on 2024-09-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedtech',
            name='technology_id',
            field=models.ManyToManyField(to='techs.technology'),
        ),
    ]
